# Generated by Django 2.1 on 2018-08-09 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('thumb_id', models.CharField(max_length=100)),
                ('date_time', models.CharField(max_length=100)),
                ('in_out_flag', models.CharField(max_length=20)),
                ('shift_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(default=datetime.datetime(2018, 8, 9, 11, 10, 1, 836478), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaidLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('del_flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('thumb_id', models.CharField(max_length=100, null=True)),
                ('shift_id', models.IntegerField(null=True)),
                ('paid_leaves', models.IntegerField()),
                ('team', models.IntegerField()),
                ('user_type', models.IntegerField()),
                ('del_flag', models.IntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
            ],
        ),
    ]
