# Generated by Django 2.1 on 2018-08-09 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=models.CharField(default=datetime.datetime(2018, 8, 9, 11, 10, 22, 227166), max_length=100),
        ),
    ]
